apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluentd.conf:
    <source>
     type tail
     format none
     path /var/log/nginx/access.log     
     tag count.format1
    </source>

    <match **>
     @type file
     path /fluentd/log/container1.log
    </match> 